master 2018.03.06.

diff --git a/sbin/ts2php b/sbin/ts2php
--- a/sbin/ts2php
+++ b/sbin/ts2php
@@ -1,12 +1,23 @@
 #!/bin/bash
-echo 'ts to php comnverter'
-if [ $# != 2 ] 
+echo 'ts to php source converter'
+echo ''
+if [ $# -eq 1 ] && [ $1 != "--help" ]
 	then
 		echo -n 'tsc start '; date +%T
 		tsc --module commonjs $1.ts 
 		echo -n 'tsc stop '; date +%T
-		rm $1.js
-		php /sbin/ts2php.php $1
+		if [ ! $? -eq 0 ]; then
+    	echo "=== Error is tsc ==="
+		else
+			rm $1.js
+			php /sbin/ts2php.php $1
+			if [ ! $? -eq 0 ]; then
+	    	echo "=== Error is ts2php ==="
+				rm $1.php
+			fi
+		fi		
 	else
-		echo 'use ts2php tsFileName (without .ts)'
+		echo ''
+		echo '   use ts2php tsFileName (without .ts)'
+		echo ''
 fi
